// Personal Information
const personalInfo = {
    name: 'Athala Angwyn Renaldi',
    role: 'Software Engineer | Backend Developer',
    bio: 'Lulusan Teknologi Informasi dengan fokus pada Software Engineering, Backend Development, dan Keamanan Sistem. Berpengalaman dalam membangun RESTful API skala enterprise menggunakan .NET, mengembangkan alat automasi, serta menciptakan ekosistem aplikasi cross-platform. Tersertifikasi ISO 27001:2022 Lead Auditor.',
    email: 'angwynren@gmail.com',
    github: 'https://github.com/athrenX',
    linkedin: 'https://linkedin.com/in/athala-angwyn-renaldi',
};

// Projects
const projects = [
    {
        title: 'Integrated Online Ticketing Ecosystem',
        description: 'Ekosistem pemesanan tiket komprehensif berbasis Web dan Mobile. Mengatasi masalah double-booking dengan implementasi Database Transaction Locking untuk menangani traffic tinggi.',
        image: 'https://via.placeholder.com/600x400/1e293b/3b82f6?text=Ticketing+System',
        techStack: ['Laravel', 'Flutter', 'MySQL', 'REST API', 'Real-time Sync'],
        github: 'https://github.com/athrenX/ticketing-system',
        live: '',
    },
    {
        title: 'Website Vulnerability Scanner',
        description: 'Aplikasi web untuk melakukan scanning kerentanan pada website untuk mendeteksi backdoor dan celah keamanan. Dikembangkan untuk Diskominfo Purwakarta.',
        image: 'https://via.placeholder.com/600x400/1e293b/3b82f6?text=Security+Scanner',
        techStack: ['Laravel 11', 'PHP', 'JavaScript', 'MySQL'],
        github: 'https://github.com/AthrenX/Web-Scanning',
        live: '',
    },
    {
        title: 'Smart Biopond System',
        description: 'Sistem automasi IoT untuk kontrol lingkungan budidaya maggot. Backend API memproses streaming data sensor DHT22 secara real-time dan memicu automasi perangkat keras.',
        image: 'https://via.placeholder.com/600x400/1e293b/3b82f6?text=IoT+Biopond',
        techStack: ['ESP32', 'C++', 'RESTful API', 'MQTT', 'IoT'],
        github: 'https://github.com/athrenX/smart-biopond',
        live: '',
    },
    {
        title: 'Kedai Es Bar 79 - Digital Ordering Platform',
// Work Experience
const experiences = [
    {
        role: 'Asisten Praktikum Laboratorium',
        company: 'Telkom University',
        startDate: 'Sep 2025',
        endDate: '',
        current: true,
        responsibilities: [
            'Pemrograman Web: Membimbing mahasiswa dalam pengembangan aplikasi web menggunakan PHP, Laravel, dan MySQL. Menjelaskan konsep MVC dan debugging kode',
            'Jaringan Komputer: Mengajarkan konfigurasi jaringan, subnetting, dan routing menggunakan Cisco Packet Tracer',
            'Bertanggung jawab atas evaluasi tugas, pelaksanaan ujian praktikum, dan memberikan feedback teknis',
        ],
    },
    {
        role: 'Freelance Full-Stack Developer',
        company: 'Kedai Es Bar 79',
        startDate: 'Oct 2025',
        endDate: 'Dec 2025',
        current: false,
        responsibilities: [
            'Membangun platform pemesanan digital berbasis web menggunakan Laravel dari nol',
            'Mengembangkan Merchant Dashboard terintegrasi untuk tracking inventaris dan pendapatan real-time',
            'Mengembangkan fitur Automated QR Code Generator untuk sistem scan-to-order',
            'Meminimalisir kesalahan pesanan saat jam sibuk dengan sistem yang lebih efisien',
        ],
    },
    {
        role: 'Application Development Intern',
        company: 'Mandiri Inhealth',
        startDate: 'Jun 2025',
        endDate: 'Sep 2025',
        current: false,
        responsibilities: [
            'Backend Developer di Departemen Pengembangan Aplikasi',
            'Merancang dan mengembangkan App Catalog API menggunakan .NET Core terintegrasi dengan React.js',
            'Mengembangkan sistem automasi backend untuk generate dokumen LOA dalam PDF, memangkas waktu proses 40%',
            'Berkolaborasi dengan tim lintas divisi untuk migrasi data dari sistem legacy dengan aman',
        ],
    },
    {
        role: 'Cyber Security Intern',
        company: 'Diskominfo Purwakarta',
        startDate: 'Jan 2025',
        endDate: 'Mar 2025',
        current: false,
        responsibilities: [
            'Menganalisis website Purwakarta yang rentan terhadap serangan backdoor dan judi online',
            'Membuat aplikasi website pendeteksi kerentanan untuk mendeteksi potensi backdoor',
            'Merancang sistem pemindaian otomatis terhadap celah keamanan pada situs web',
            'Memberikan rekomendasi dan dokumentasi hasil analisis keamanan kepada tim IT Diskominfo',
        ],
    },
];      company: 'StartUp Solutions',
        startDate: 'Mar 2021',
        endDate: 'Dec 2022',
        current: false,
        responsibilities: [
            'Developed and maintained web applications using PHP and MySQL',
            'Optimized database queries improving performance by 40%',
            'Integrated third-party APIs and payment gateways',
            'Participated in agile development process and sprint planning',
        ],
    },
    {
        role: 'Junior Developer',
        company: 'Digital Agency',
// Certificates
const certificates = [
    {
        name: 'ISO/IEC 27001:2022 Lead Auditor',
        issuer: 'Mastermind Assurance',
        date: 'Dec 2025',
        credentialId: 'Valid until Dec 2028',
        credentialUrl: '',
    },
    {
        name: 'ISO 27001:2022 Lead Auditor Training',
        issuer: 'Cisometry Academy',
        date: 'Sep 2025',
        credentialId: '',
        credentialUrl: '',
    },
    {
        name: 'Offensive Security Training',
        issuer: 'Cisometry Academy',
        date: 'Sep 2025',
        credentialId: '',
        credentialUrl: '',
    },
    {
        name: 'SOC Analyst Training',
        issuer: 'PT Media Telekomunikasi Mandiri (MTM)',
        date: 'Sep 2025',
        credentialId: '',
        credentialUrl: '',
    },
    {
        name: 'Application Development Internship',
        issuer: 'Mandiri Inhealth',
        date: 'Sep 2025',
        credentialId: '',
        credentialUrl: '',
    },
    {
        name: 'Cyber Security Internship',
        issuer: 'Diskominfo Purwakarta',
        date: 'Mar 2025',
        credentialId: '',
        credentialUrl: '',
    },
    {
        name: 'Asisten Praktikum Pemrograman Web',
        issuer: 'Telkom University',
        date: 'Jan 2026',
        credentialId: '',
        credentialUrl: '',
    },
    {
        name: 'Asisten Praktikum Jaringan Komputer',
        issuer: 'Telkom University',
        date: 'Jan 2026',
        credentialId: '',
        credentialUrl: '',
    },
];      issuer: 'Oracle',
        date: 'May 2024',
        credentialId: 'ORA-11223344',
        credentialUrl: 'https://oracle.com/certification',
    },
    {
        name: 'Web Development Bootcamp',
        issuer: 'Udemy',
        date: 'Jan 2024',
        credentialId: 'UC-ABCD1234',
        credentialUrl: 'https://udemy.com/certificate',
    },
];
